# docker-compose.custom.yml - Solo backend, gateway y BD (sin frontend)

include:
  - path: compose/core.yml
    project_directory: .

services:
  # Elimina el frontend del core
  frontend:
    profiles:
      - disabled

volumes:
  openmrs-data:
  db-data:
  db-backup:

networks:
  default:
    driver: bridge
  services-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/24