#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

OUTPUT_FILE="${1:-.env.production}"

if [ -e "$OUTPUT_FILE" ]; then
  echo "Refusing to overwrite $OUTPUT_FILE. Move it first if you intend to rotate credentials." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required" >&2
  exit 1
fi

umask 077

secret() {
  openssl rand -hex 24
}

MYSQL_OPENMRS_PASSWORD="$(secret)"
MYSQL_ROOT_PASSWORD="$(secret)"
OMRS_DB_REPL_PASSWORD="$(secret)"
OMRS_DB_BACKUP_PASSWORD="$(secret)"
KEYCLOAK_ADMIN_PASSWORD="$(secret)"
KC_DB_PASSWORD="$(secret)"
OAUTH2_CLIENT_SECRET="$(secret)"
GRAFANA_ADMIN_PASSWORD="$(secret)"
FUA_DB_PASSWORD="$(secret)"
FUA_TOKEN="$(secret)"
FUA_SECRET_KEY="$(secret)"
HAPI_DB_PASSWORD="$(secret)"
REPORTES_DB_PASSWORD="$(secret)"

cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/security/secrets_generate.sh
# This file contains plaintext credentials. Keep mode 600 and store backups encrypted.

# Core MariaDB
OPENMRS_DB_USER=openmrs
MYSQL_OPENMRS_PASSWORD=${MYSQL_OPENMRS_PASSWORD}
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
OMRS_DB_REPL_USER=openmrs_repl
OMRS_DB_REPL_PASSWORD=${OMRS_DB_REPL_PASSWORD}
OMRS_DB_BACKUP_USER=openmrs_backup
OMRS_DB_BACKUP_PASSWORD=${OMRS_DB_BACKUP_PASSWORD}
OMRS_OCL_TOKEN=

# Pin immutable image tags before production deployment.
BACKEND_TAG=latest
FRONTEND_SOURCE_TAG=latest
FRONTEND_RUNTIME_TAG=latest
STRIP_SOURCE_MAPS=true

# Keycloak
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
KC_DB_DATABASE=keycloak
KC_DB_USERNAME=keycloak
KC_DB_PASSWORD=${KC_DB_PASSWORD}
KEYCLOAK_MODE=development
KC_HOSTNAME=http://localhost/keycloak
KEYCLOAK_PORT=8180
KEYCLOAK_PUBLIC_URL=http://localhost/keycloak
OPENMRS_REDIRECT_URI=http://localhost/openmrs/*
OAUTH2_CLIENT_SECRET=${OAUTH2_CLIENT_SECRET}

# Monitoring
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

# FUA
SIHSALUS_FUA_GEN_DB_USER=fuagenerator
SIHSALUS_FUA_GEN_DB_PASSWORD=${FUA_DB_PASSWORD}
SIHSALUS_FUA_GEN_DB=fuagenerator
SIHSALUS_FUA_GEN_TOKEN=${FUA_TOKEN}
SIHSALUS_FUA_GEN_SECRET_KEY=${FUA_SECRET_KEY}

# HAPI FHIR
HAPI_DB_USER=hapi
HAPI_DB_PASSWORD=${HAPI_DB_PASSWORD}
HAPI_DB_NAME=hapi

# Indicadores
SIHSALUS_REPORTES_SQL_DB=reportes_sql
SIHSALUS_REPORTES_SQL_DB_USER=reportes_sql
SIHSALUS_REPORTES_SQL_DB_PASSWORD=${REPORTES_DB_PASSWORD}
EOF

chmod 600 "$OUTPUT_FILE"
echo "Generated $OUTPUT_FILE with mode 600. Review URLs and pin image tags before deployment."
